#!/bin/zsh
# hairlinehd's bspwm autostart file

# mount disks
udisksctl mount -b /dev/sdd1
udisksctl mount -b /dev/sdb1
udisksctl mount -b /dev/sdc

# start once to prevent duplicate processes
run plank
run picom
run notification
run polkit-gnome
run clearfullscreen
run polylaunch
run otd-daemon

# run always
rm .xsession-errors*
setwallpaper --randomize ~/.local/wallpapers/
xset -dpms
xset s off

# weird exceptions
sleep 2
run clipit
run nm-applet
run volnoti-dbus
run swallow

# fixes plank and notification
bspc subscribe node_add | while read -r _; do
   xdo raise -N Plank
done 

bspc subscribe node_add | while read -r _; do
   xdo raise -N Notification
done 


