#!/bin/sh
# hairlinehd's bspwm config

xrandr --output DP-1 --mode 1920x1080 --rate 165 --rotate normal --primary
#xrandr --output DVI-I-1 --mode 1600x900 --pos 1920x180 --rotate normal
xrandr --output DVI-I-1 --off

run sxhkd

# workspaces
bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DVI-I-1 -d 6

# autostart
~/.config/autostart/bspwm &

# rules
~/.config/bspwm/rules &

# config
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"
bspc config border_width 1.6
bspc config pointer_motion_interval 3

