#!/bin/sh 
# hairlinehd's sxhkd config

## -- for environment variables 
source /home/isao/.config/zsh/.zshenv

## -- wm independent keybinds

# logout
super + shift + q
  pkill -u $USER

# close window
super + q
  xdo close && ofi

# kill window
super + F4
  xdo kill

# terminal
super + Return
  $TERMINAL

# browser
super + w
  $BROWSER --enable-features=WebUIDarkMode --force-dark-mode 

# restart sxhkd
super + Escape
  pkill -usr1 -x sxhkd && notify-send -t 500 'sxhkd' 'sxhkd restarted'

# dmenu
super + p
  dmenu_run

# music player
super + m
  $AUDIO

# video player
super + v
  $VIDEO


# search
super + d
  $HOME/.config/rofi/launchers/type-3/launcher.sh

# file manager
super + e
  $FILEMANAGER

# screenshot
Print
  screenshot full

# selection screenshot
ctrl + Print
  screenshot select

# qr code
shift + Print
  screenshot qr

# image viewer
super + i
  $IMAGE

# mute
XF86AudioMute
  volctl mute

# decrease volume
XF86AudioLowerVolume
  volctl dec 5

# increase volume
XF86AudioRaiseVolume
  volctl inc 5

# previous track
XF86AudioPrev
  volctl previous

# toggle play
XF86AudioPlay
  volctl toggle

# next track
XF86AudioNext
  volctl next

# mute mic
Pause
  volctl mute-mic

# lock screen
super + shift + l
  betterlockscreen -l

# game optimizations
super + g
  launchgame fix

## -- only for bspwm

# reload bspwm
super + shift + r
  bspc wm -r && notify-send "bspc" "wm restarted"

# switch workspace
super + {0-6}
  bspc desktop -f {0-6}

# throw window into workspace
super + shift + {0-6}
  bspc node -d {0-6}

## switch window with direction
super + shift + {h,j,k,l}
  bspc node -s {west,south,north,east}

## focus window with direction
super + {h,j,k,l}
  bspc node -f {west,south,north,east}

## toggle fullscreen
super + f
  bspc node -t \~fullscreen

## toggle floating
super + s
  bspc node -t \~floating

## toggle tilling
super + t
  bspc node -t \~tiled


 
